### PR TITLE
Add MySQL implementation

### PR DESCRIPTION
**Pull request by steventwheeler**
References #802

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @steventwheeler,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by steventwheeler** [comment]
I'm working on getting the CLA approved on my end but this change appears to resolve the issues I was seeing in my application.

**Comment by lightbend-cla-validator** [comment]
Hi @steventwheeler,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by steventwheeler** [comment]
My employer has signed the CLA.

**Comment by octonato** [comment]
> My employer has signed the CLA.

Thanks for your contribution @steventwheeler. 

However, for the CLA, the one that contributed needs to sign. The CLA checker will verify if user `@steventwheeler` has signed.

**Comment by octonato** [comment]
> > My employer has signed the CLA.
> 
> Thanks for your contribution @steventwheeler.
> 
> However, for the CLA, the one that contributed needs to sign. The CLA checker will verify if user `@steventwheeler` has signed.

So, what I'm saying is, if you have their authorization to contribute code to Akka, then you can sign the CLA and the code can be accepted by Lightbend.

**Comment by steventwheeler** [comment]
> > > My employer has signed the CLA.
> > 
> > 
> > Thanks for your contribution @steventwheeler.
> > However, for the CLA, the one that contributed needs to sign. The CLA checker will verify if user `@steventwheeler` has signed.
> 
> So, what I'm saying is, if you have their authorization to contribute code to Akka, then you can sign the CLA and the code can be accepted by Lightbend.

I have signed it as well.

**Comment by steventwheeler** [comment]
Or at least I linked my GitHub account to your site and filled in the form. Is there another step that is required?

**Comment by johanandren** [comment]
I manually verified there is an entry in the CLA database 👍

**Review by johanandren — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
closing and reopen to re-trigger the CLA check

**Review by octonato — APPROVED** [review]
LGTM
Thanks @steventwheeler for the contribution.

**Comment by johanandren** [comment]
Hey @steventwheeler, unfortunately we had an issue with the CI setup and didn't notice that the `MySQLScalaJdbcDurableStateChangesByTagTest` doesn't pass from this PR, I've disabled it in #806 where I fix the CI jobs, would be great if you could take a look, seems like the `MySQLSequenceNextValUpdater` doesn't work as expected.

**Comment by Roiocam** [comment]
> Hey @steventwheeler, unfortunately we had an issue with the CI setup and didn't notice that the `MySQLScalaJdbcDurableStateChangesByTagTest` doesn't pass from this PR, I've disabled it in #806 where I fix the CI jobs, would be great if you could take a look, seems like the `MySQLSequenceNextValUpdater` doesn't work as expected.

@johanandren Seems like MySQL can only increase the sequence by inserting and from the database itself. I will say the Oracle and SQLServer will be more easy to implement. Need some magic tricks that make MySQL work.

**Pull request merged**
