### PR TITLE
#502 Fix problem with Oracle schema.

### PR DESCRIPTION
**Pull request by skisel**
References #502

### CODE REVIEW

**Comment by skisel** [comment]
Not sure the build error is actually triggered by my change

**Comment by octonato** [comment]
@skisel, the build failed for an unrelated reason. 

Your PR makes sense and that was certainly a oversight. That column was probably renamed on the original PR and we forgot to change it for the Oracle schema. 

I'm surprised that we didn't notice it because we use the schema file to generate the schema when testing. So, that should have been raised as a build failure.

**Comment by octonato** [comment]
this build is blocked for unknown reason. I will close and reopen this PR.

**Comment by skisel** [comment]
Oracle tests failed for some other issue it seems

**Comment by octonato** [comment]
@skisel, the Oracle failed because of the changes in this PR. 

```
2021-03-05 17:21:55,947 - akka.persistence.jdbc.query.QueryTestSpec$TestActor -> ERROR[test-akka.actor.default-dispatcher-8] [akka://test/user/$a test QueryTestSpec$TestActor - Failed to persist event type [akka.persistence.journal.Tagged] with sequence number [1] for persistenceId [my-1].
java.sql.SQLSyntaxErrorException: ORA-00904: "EVENT_MANIFEST": invalid identifier
```

Somewhere there is some code using the old `EVENT_MANIFEST` column. That's actually good news. I was surprised that we were not detecting it before in the tests. The drawback being that there is more work to do on this PR.

**Comment by skisel** [comment]
Thanks for helping out with the analysis what failed. I pushed the fix

**Review by octonato — APPROVED** [review]
LGMT

Thanks @skisel

**Pull request merged**
