### PR TITLE
Optimize query of highest seq number

### PR DESCRIPTION
**Pull request by samfrown**
References #400 

Change highest sequence number queries to simplify generated sql

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by renatocaval** [comment]
@samfrown, thanks for this contribution. 

We are about to release v4.0.0 and I would like to suggest that you re-target this fix to the `master` branch instead of `3.5.x`. We are not planning to release from `3.5.x` branch anymore, unless serious bug is found. 

The release process and groupId changed since it moved under the Akka org and it make it much easier for us to not keep releasing old branches.

We can include your fix in `v4.0.1`. 
The reason it's preferable to not include it in `4.0.0`, is that we have already cut a RC and since this is not a critical bug fix, we prefer that `4.0.0` to be the same as `4.0.0-RC2`. I hope you understand.

We can cut v4.0.1 short after.

**Comment by samfrown** [comment]
@renatocaval Finally I have been able to rebase the branch as you asked

**Comment by renatocaval** [comment]
Thanks @samfrown

**Pull request merged**
