### PR TITLE
Removes logical deletion

### PR DESCRIPTION
**Pull request by nvollmar**
References #557

### CODE REVIEW

**Comment by ignasi35** [comment]
Thanks @nvollmar for puting this in motion.

This is a rather important behavioral change so, IMHO it should be prominently explained on the docs and release notes. Maybe even justifies the bump of the MAJOR version of the plugin (as a user I'd be very pissed if a PATCH release included such a change sneakily).

Would you be able to review the docs for places where delete is mentioned and amend them? Thanks!

**Comment by ignasi35** [comment]
In general, SQL queries must still filter by `logicalDeletion.enable = false` but maybe when the flag to hard-delete is enabled we can remove the filter by `journal.deleted=false` criteria from the SLQ statement. Not on this PR though, that could be a future improvement.

**Comment by ignasi35** [comment]
Do we already have documentation on the safest procedure to move from `logicalDeletion.enable = false` to `logicalDeletion.enable = true` (and back in case of a rollback)? Maybe for a separate PR too.

**Comment by nvollmar** [comment]
I agree that this would be quite a significant change that should be mentioned prominently in the release notes. As mentioned in Issue #557, this feature is deprecated and warned. If a major release is warranted, then the feature might also be removed at the same time to clean everything up.

I didn't find any relevant mentioning of deletion in the docs.

**Comment by nvollmar** [comment]
There is no mentioning of logical deletion anywhere in the `docs` folder of the project

**Comment by ignasi35** [comment]
Thanks for checking.

Maybe, since there's already a deprecation warning and changing the default value of the setting already requires a MAJOR version bump, maybe we could just drop the setting and the feature altogether so users migrating to that major version will have to adopt the new behavior.

**Comment by nvollmar** [comment]
I've added the removal of this feature to this PR

**Review by ignasi35 — COMMENTED** [review]
Nice! thanks @nvollmar

**Comment by octonato** [comment]
@nvollmar, we will need MiMa exclusions.

**Comment by nvollmar** [comment]
@octonato Added mima excludes

**Review by patriknw — APPROVED** [review]
LGTM

**Comment by patriknw** [comment]
@nvollmar sorry for the delay here. Would you be able to fix the conflicts? I think this is ready to be merged after that.

**Comment by patriknw** [comment]
@nvollmar `OracleScalaEventAdapterTest` is failing here. Do you think it can be related to the changes in this PR? I have re-run it at least twice.

Also ran it successfully on master in https://github.com/akka/akka-persistence-jdbc/pull/672

**Comment by patriknw** [comment]
Note that the failing job is running with some custom parameters:
```
sbt "++2.13.4 It/testOnly akka.persistence.jdbc.integration.Oracle*"   -Djdbc-journal.dao=akka.persistence.jdbc.journal.dao.legacy.ByteArrayJournalDao -Djdbc-snapshot-store.dao=akka.persistence.jdbc.snapshot.dao.legacy.ByteArraySnapshotDao -Djdbc-read-journal.dao=akka.persistence.jdbc.query.dao.legacy.ByteArrayReadJournalDao
```

**Comment by nvollmar** [comment]
I'll have to backtrack the changes and see what might cause this

**Comment by patriknw** [comment]
I'm quite convinced that the Oracle case in akka.persistence.jdbc.query.dao.legacy.ByteArrayReadJournalDao was broken already before this change when using logicalDelete=false
That shows up now when the default has been changed.
I verified that in https://github.com/akka/akka-persistence-jdbc/pull/672

I will merge this and then mark the failing tests as pending in a separate PR. I don't think we care that much about the legacy.ByteArrayReadJournalDao

**Pull request merged**
